// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// effort_sim
List effort_sim(NumericVector Bini, NumericVector K, NumericVector r, NumericMatrix qflt, int Time, NumericVector Effort, NumericVector lambda, NumericMatrix Pprey, NumericVector Xp, NumericVector mu, NumericVector Eff, int np, NumericVector Ispredation);
RcppExport SEXP _RcppSimEffort_effort_sim(SEXP BiniSEXP, SEXP KSEXP, SEXP rSEXP, SEXP qfltSEXP, SEXP TimeSEXP, SEXP EffortSEXP, SEXP lambdaSEXP, SEXP PpreySEXP, SEXP XpSEXP, SEXP muSEXP, SEXP EffSEXP, SEXP npSEXP, SEXP IspredationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Bini(BiniSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type K(KSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type qflt(qfltSEXP);
    Rcpp::traits::input_parameter< int >::type Time(TimeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Effort(EffortSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Pprey(PpreySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xp(XpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Eff(EffSEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Ispredation(IspredationSEXP);
    rcpp_result_gen = Rcpp::wrap(effort_sim(Bini, K, r, qflt, Time, Effort, lambda, Pprey, Xp, mu, Eff, np, Ispredation));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppSimEffort_effort_sim", (DL_FUNC) &_RcppSimEffort_effort_sim, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppSimEffort(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
