# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

effort_sim <- function(Bini, K, r, qflt, Time, Effort, lambda, Pprey, Xp, mu, Eff, np, Ispredation) {
    .Call(`_RcppSimEffort_effort_sim`, Bini, K, r, qflt, Time, Effort, lambda, Pprey, Xp, mu, Eff, np, Ispredation)
}

